# Generated by Django 3.0.5 on 2020-06-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('1', 'CS'), ('2', 'MATHS'), ('3', 'GK')], max_length=1)),
                ('ans1', models.CharField(max_length=20)),
                ('ans2', models.CharField(max_length=20)),
                ('ans3', models.CharField(max_length=20)),
                ('ans4', models.CharField(max_length=20)),
                ('corrans',models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
