# Generated by Django 3.0.5 on 2020-06-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='corrans',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
    ]
