# Generated by Django 3.0.5 on 2020-06-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tys', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
