# Generated by Django 3.0.5 on 2020-06-24 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tys', '0004_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
